services:
  app:
    build:
      context: .
    ports:
      - "5010:4000"
    volumes:
      - ./data:/data
    env_file: .env
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: ${PM_CPU_RESERVATION}
          memory: ${PM_MEM_RESERVATION}
        limits:
          cpus: ${PM_CPU_LIMIT}
          memory: ${PM_MEM_LIMIT}
