services:
  app:
    build:
      context: .
    ports:
      - "5010:4000"
    volumes:
      - ./data:/data
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
